state_estimator:
  ros__parameters:
    timer_frequency: 1.0 # [Hz]
    initial_x: 0.0 # Initial x position [m]
    initial_y: 0.0 # Initial y position [m]
    initial_theta: 0.0 # Initial orientation [rad]
    wheel_radius: 0.035 # Wheel radius [m]
    front_wheel_base: 0.131889 # Middle Wheel to Front Wheel distance along the Robot X-axis [m]
    rear_wheel_base: 0.118112 # Middle Wheel to Rear Wheel distance along the Robot X-axis [m]
    base_to_wheel_height: 0.044850 # Height of the steering pivot above the wheel axle [m]
    max_steering_front: 0.610865 # Front wheel max steering angle [rad] (35.0 deg)
    max_steering_rear: 0.610865 # Rear wheel max steering angle [rad] (35.0 deg)
