"""
create_urdf.py
──────────────
Post-processes the URDF generated by onshape-to-robot:

  1. Rewrites mesh URIs to the correct ROS package path.
  2. Injects a `base_link_centered` link connected to the original
     `base_link` (the onshape-to-robot exported frame) via a computed
     fixed joint that places base_link_centered at the kinematic centre
     of the rover with the correct REP-105 orientation:
       x = forward,  y = left,  z = same as base_link (not ground-projected)
  3. Corrects the zero-angle offset of the rear steering joints so that
     a joint command of 0 rad produces straight-ahead wheel alignment.

TF tree produced
────────────────
  map (static)
   └─ odom                    ← state_estimation node publishes this at startup
       └─ base_footprint      ← state_estimation node drives this (z=0, x/y/θ only)
            └─ base_link_centered  ← robot_state_publisher from URDF (fixed joint)
                 └─ base_link      ← original onshape-to-robot frame (kept as-is)
                      └─ wheels, sensors, etc.

base_link_centered vs base_link
────────────────────────────────
`base_link` is wherever onshape-to-robot placed the exported frame — the
CAD part origin, which may not be at the kinematic centre of the robot
and may have a different axis orientation.

`base_link_centered` is injected by this script. It sits at the kinematic
centre (midpoint of front/rear axles, laterally centred) with the correct
REP-105 axis orientation. Its z is inherited from base_link — it is NOT
ground-projected. The ground projection (z=0) is handled by base_footprint,
which is published dynamically by the state estimation node.

base_footprint is NOT in the URDF. It is the 2D ground-plane projection
of base_link_centered published by the state estimation node:
  base_footprint: same (x, y, θ) as base_link_centered but z=0, roll=0, pitch=0.

Frame detection
───────────────
The parser checks whether same-side joints (e.g. bl + fl = left side)
share an x or y value to determine whether the URDF is in the old CAD
frame (x = lateral, y = longitudinal, forward = -y) or already REP-105
aligned (x = forward, y = lateral). The correction rotation and
translation are derived accordingly.

Rear steering zero offset
──────────────────────────
The physical rear steering arms have a 10 degree mechanical offset from
the Onshape CAD zero position. Correcting this in the URDF only requires
updating the joint <origin> yaw so the child link (the steering arm) is
rotated to its true straight-ahead pose when the joint variable reads 0.

The Onshape joint limits are already set symmetrically around the physical
zero (i.e. the CAD limits already account for the offset), so the limit
bounds do not need to be modified.

  Example for REAR_STEERING_ZERO_OFFSET_RAD = +0.17453 (+10 deg):
    origin yaw:   old_yaw + 0.17453
    lower limit:  unchanged
    upper limit:  unchanged
"""

from __future__ import annotations

import math
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

# Joints whose physical zero position is offset from the Onshape CAD zero.
# Each entry maps a joint name to the correction in radians to add to the
# joint origin yaw. The limit bounds are shifted by the negative of this
# value to preserve the physical range of motion.
#
# Positive = counterclockwise when viewed from above (right-hand rule, +z up).
# Negate this value if the wheels toe inward instead of pointing straight.
JOINT_ZERO_OFFSETS_RAD: dict[str, float] = {
    "bl_steering": math.radians(10.0),
    "br_steering": math.radians(10.0) * -1.0,
}


# ─────────────────────────────────────────────────────────────────────────────
# onshape-to-robot runner
# ─────────────────────────────────────────────────────────────────────────────

def run_onshape_to_robot(target_dir: str | Path | None = None) -> None:
    """Run onshape-to-robot to (re)generate the URDF and meshes.

    Args:
        target_dir: Directory to run the tool in. Defaults to the package dir.
    """
    script_dir = Path(__file__).resolve().parent   # .../perseverance/urdf
    package_dir = Path(target_dir) if target_dir else script_dir.parent
    if not package_dir.exists():
        raise FileNotFoundError(
            f"Target directory does not exist: {package_dir}")

    venv_tool = package_dir.parent / ".venv" / "bin" / "onshape-to-robot"
    cmd_path = str(venv_tool) if venv_tool.exists(
    ) else shutil.which("onshape-to-robot")
    if not cmd_path:
        raise RuntimeError(
            "onshape-to-robot not found. Install it (preferably in .venv) or add to PATH.")

    print(f"Running: {cmd_path} . (cwd={package_dir})")
    try:
        subprocess.run([cmd_path, "."], cwd=str(package_dir), check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"onshape-to-robot failed (exit {e.returncode})") from e
    print("onshape-to-robot conversion completed")


# ─────────────────────────────────────────────────────────────────────────────
# Geometry helpers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_xyz(origin_elem: ET.Element | None) -> tuple[float, float, float]:
    """Extract (x, y, z) floats from a URDF <origin xyz="..."/> element."""
    if origin_elem is None:
        return 0.0, 0.0, 0.0
    parts = origin_elem.get("xyz", "0 0 0").split()
    return float(parts[0]), float(parts[1]), float(parts[2])


def _compute_base_link_centered_joint(urdf_text: str) -> tuple[float, float, float, float, float, float]:
    """
    Parse the URDF and return (tx, ty, tz, roll, pitch, yaw) for the
    base_link_centered_to_base_link fixed joint.

    The translation places base_link_centered at the kinematic centre of the
    rover (midpoint between front/rear wheel axles and left/right pivots).
    The rotation corrects the CAD frame orientation to REP-105.
    z is inherited from base_link — this frame is NOT ground-projected.
    The ground projection is base_footprint, published dynamically by the
    state estimation node.

    Frame detection
    ───────────────
    Same-side joints (e.g. bl_steering + fl_steering = left side) always share
    one coordinate:
      - If they share x  →  x is the lateral axis  →  old CAD frame (forward = -y)
      - If they share y  →  y is the lateral axis  →  REP-105 frame (forward = +x)

    This test is robust regardless of whether track width ≈ wheelbase.

    Returns
    ───────
    (tx, ty, tz, roll, pitch, yaw) in metres / radians, expressing the position
    and orientation of base_link's origin in the base_link_centered frame.
    """
    root = ET.fromstring(urdf_text)

    # Collect (x, y) origins of all steering joints
    steering_origins: list[tuple[float, float]] = []
    for joint in root.iter("joint"):
        if not joint.get("name", "").endswith("_steering"):
            continue
        x, y, _ = _parse_xyz(joint.find("origin"))
        steering_origins.append((x, y))

    if len(steering_origins) < 2:
        raise ValueError(
            f"Found only {len(steering_origins)} '_steering' joints — need at least 2."
        )

    # ── Frame orientation detection ───────────────────────────────────────────
    # Group joints by rounded y value. In the old CAD frame, joints on the same
    # front/rear row share a y value but have different x values (left vs right).
    # If every y-group contains joints with varying x, then x is lateral → CAD frame.
    groups_by_y: dict[float, list[float]] = {}
    for x, y in steering_origins:
        key = round(y, 3)
        groups_by_y.setdefault(key, []).append(x)

    # Old CAD frame: each y-group (same row) has multiple distinct x values
    old_cad_frame = all(
        max(xs) - min(xs) > 0.05
        for xs in groups_by_y.values()
        if len(xs) >= 2
    )

    if old_cad_frame:
        # x = lateral (left = +x),  y = longitudinal (forward = -y)
        front_y = sum(y for _, y in steering_origins if y < 0) / max(
            1, sum(1 for _, y in steering_origins if y < 0))
        rear_y = sum(y for _, y in steering_origins if y > 0) / max(
            1, sum(1 for _, y in steering_origins if y > 0))
        left_x = sum(x for x, _ in steering_origins if x > 0) / max(
            1, sum(1 for x, _ in steering_origins if x > 0))
        right_x = sum(x for x, _ in steering_origins if x < 0) / max(
            1, sum(1 for x, _ in steering_origins if x < 0))

        kin_x_cad = (left_x + right_x) / 2.0
        kin_y_cad = (front_y + rear_y) / 2.0

        # +90° rotation: CAD x=lateral/y=longitudinal → REP x=fwd/y=left
        #   x_rep = -y_cad,   y_rep = x_cad
        # Translation: place base_link origin (0,0 in CAD) at the correct
        # position in base_footprint frame:
        #   (tx, ty) = -R(yaw) * (kin_x_cad, kin_y_cad)
        yaw = math.pi / 2.0
        tx = -(math.cos(yaw) * kin_x_cad - math.sin(yaw) * kin_y_cad)
        ty = -(math.sin(yaw) * kin_x_cad + math.cos(yaw) * kin_y_cad)

    else:
        # REP-105 already: x = forward,  y = lateral (left = +y)
        front_x = sum(x for x, _ in steering_origins if x > 0) / max(
            1, sum(1 for x, _ in steering_origins if x > 0))
        rear_x = sum(x for x, _ in steering_origins if x < 0) / max(
            1, sum(1 for x, _ in steering_origins if x < 0))
        left_y = sum(y for _, y in steering_origins if y > 0) / max(
            1, sum(1 for _, y in steering_origins if y > 0))
        right_y = sum(y for _, y in steering_origins if y < 0) / max(
            1, sum(1 for _, y in steering_origins if y < 0))

        kin_x = (front_x + rear_x) / 2.0
        kin_y = (left_y + right_y) / 2.0

        # No rotation needed — just shift to kinematic centre
        tx = -kin_x
        ty = -kin_y
        yaw = 0.0

    return tx, ty, 0.0, 0.0, 0.0, yaw


def _build_base_link_centered_xml(tx: float, ty: float, tz: float,
                                  roll: float, pitch: float, yaw: float) -> str:
    """Return the XML block for base_link_centered and its fixed joint to base_link."""
    return (
        "\n"
        "  <!-- base_link_centered: kinematic centre of the rover, REP-105 oriented -->\n"
        "  <!-- x=forward, y=left, z=up. z is NOT ground-projected (that is base_footprint). -->\n"
        "  <!-- base_footprint is published dynamically by the state estimation node. -->\n"
        "  <link name=\"base_link_centered\"/>\n"
        "\n"
        "  <joint name=\"base_link_centered_to_base_link\" type=\"fixed\">\n"
        "    <parent link=\"base_link_centered\"/>\n"
        "    <child link=\"base_link\"/>\n"
        f"    <!-- xyz: base_link origin in base_link_centered frame (auto-computed) -->\n"
        f"    <!-- rpy: CAD-frame to REP-105 correction (yaw={math.degrees(yaw):.1f} deg) -->\n"
        f"    <origin xyz=\"{tx:.6f} {ty:.6f} {tz:.6f}\""
        f" rpy=\"{roll:.6f} {pitch:.6f} {yaw:.6f}\"/>\n"
        "  </joint>\n"
    )


def _apply_joint_zero_offsets(text: str) -> str:
    """
    Correct joint origin yaws and limit bounds for joints with a mechanical
    zero offset defined in JOINT_ZERO_OFFSETS_RAD.

    For each affected joint the URDF <origin> rpy yaw is updated and both
    <limit> bounds are shifted by the negative offset so the physical
    travel range is preserved.

    This operates on the raw URDF text using targeted regex substitution
    rather than a full XML parse/serialise round-trip to avoid disturbing
    the formatting and floating-point representation of unrelated elements.

    Args:
        text: Raw URDF file content.

    Returns:
        Updated URDF content with corrected joint origins and limits.
    """
    for joint_name, offset_rad in JOINT_ZERO_OFFSETS_RAD.items():

        # Match the entire <joint name="..."> ... </joint> block.
        joint_pattern = re.compile(
            rf'(<joint\s+name="{re.escape(joint_name)}".*?</joint>)',
            re.DOTALL,
        )
        match = joint_pattern.search(text)
        if not match:
            print(
                f"  Warning: joint '{joint_name}' not found — skipping zero offset.")
            continue

        joint_xml = match.group(1)

        # ── Update origin yaw ─────────────────────────────────────────────────
        # The <origin> rpy attribute holds "roll pitch yaw" as space-separated
        # floats. We extract the current yaw, add the offset, and write it back.
        origin_match = re.search(
            r'<origin\s+([^/]*?)/?>', joint_xml, re.DOTALL)
        if not origin_match:
            print(
                f"  Warning: no <origin> in '{joint_name}' — skipping zero offset.")
            continue

        origin_tag = origin_match.group(0)
        rpy_match = re.search(r'rpy="([^"]+)"', origin_tag)

        if rpy_match:
            rpy_vals = rpy_match.group(1).split()
            roll, pitch = float(rpy_vals[0]), float(rpy_vals[1])
            old_yaw = float(rpy_vals[2])
            new_yaw = old_yaw + offset_rad
            new_rpy_str = f"{roll} {pitch} {new_yaw:.6f}"
            new_origin_tag = origin_tag.replace(rpy_match.group(0),
                                                f'rpy="{new_rpy_str}"')
        else:
            # No rpy attribute present — add it with the offset as the yaw
            new_origin_tag = origin_tag.replace(">",
                                                f' rpy="0 0 {offset_rad:.6f}">')
            old_yaw = 0.0

        joint_xml = joint_xml.replace(origin_tag, new_origin_tag)

        text = text.replace(match.group(1), joint_xml)
        print(
            f"  Applied zero offset to '{joint_name}': "
            f"yaw {math.degrees(old_yaw):.3f} -> {math.degrees(old_yaw + offset_rad):.3f} deg"
        )

    return text


# ─────────────────────────────────────────────────────────────────────────────
# Main post-processing function
# ─────────────────────────────────────────────────────────────────────────────

def clean_urdf(urdf_filename: str) -> None:
    """Clean and post-process the URDF generated by onshape-to-robot.

    Transformations applied
    ───────────────────────
    1. Rewrite mesh URIs to the correct ROS package path.
    2. Inject a base_footprint link + fixed joint (auto-computed from wheel
       geometry) as the REP-105 compliant root link.
    3. Correct joint zero offsets for rear steering arms so that a command
       of 0 rad drives straight ahead (see JOINT_ZERO_OFFSETS_RAD).

    Args:
        urdf_filename: Filename of the URDF (e.g., 'rover.urdf').
    """
    script_dir = Path(__file__).resolve().parent
    urdf_path = (script_dir / urdf_filename).resolve()
    if not urdf_path.exists():
        raise FileNotFoundError(f"URDF file not found: {urdf_path}")

    text = urdf_path.read_text(encoding="utf-8")

    # ── Step 1: rewrite mesh URIs ─────────────────────────────────────────────
    # onshape-to-robot emits e.g. "package://meshes/foo.stl" or
    # "package://perseverance/meshes/foo.stl"; normalise both to
    # "package://perseverance/urdf/foo.stl" so RViz can resolve them.
    text = re.sub(
        r'package://[^"]*?([^/\s"]+\.stl)',
        r'package://perseverance/urdf/\1',
        text,
    )

    # ── Step 2: inject base_link_centered (idempotent — skipped if already present) ──
    if "base_link_centered" not in text:
        tx, ty, tz, roll, pitch, yaw = _compute_base_link_centered_joint(text)
        centered_xml = _build_base_link_centered_xml(
            tx, ty, tz, roll, pitch, yaw)

        # Insert immediately after the opening <robot ...> tag
        m = re.search(r"<robot\b[^>]*>", text)
        if not m:
            raise ValueError("Could not find <robot> tag in URDF.")
        text = text[:m.end()] + centered_xml + text[m.end():]

        print(
            f"Injected base_link_centered: "
            f"xyz=({tx:.4f}, {ty:.4f}, {tz:.4f})  "
            f"yaw={math.degrees(yaw):.1f} deg"
        )
    else:
        print("base_link_centered already present — skipping injection.")

    # ── Step 3: correct rear steering joint zero offsets ─────────────────────
    print("Applying joint zero offsets:")
    text = _apply_joint_zero_offsets(text)

    urdf_path.write_text(text, encoding="utf-8")


def _parse_rpy(origin_elem: ET.Element | None) -> tuple[float, float, float]:
    """Extract (roll, pitch, yaw) floats from a URDF <origin rpy="..."/> element."""
    if origin_elem is None:
        return 0.0, 0.0, 0.0
    parts = origin_elem.get("rpy", "0 0 0").split()
    return float(parts[0]), float(parts[1]), float(parts[2])


def _get_joint(root: ET.Element, name: str) -> ET.Element:
    for joint in root.iter("joint"):
        if joint.get("name") == name:
            return joint
    raise ValueError(f"Joint '{name}' not found in URDF.")


def _derive_rover_geometry(urdf_text: str) -> dict[str, float]:
    """
    Derive rover geometry constants from joint origins in the URDF.

    The URDF is in the old CAD frame (x=lateral, y=longitudinal, forward=-y)
    so coordinate axes are remapped to REP-105 (x=forward, y=left) before
    computing distances.

    Parameters derived
    ──────────────────
    front_wheel_base   : distance along REP-105 x (forward) from middle wheel
                         axle to front steering pivot [m]
    rear_wheel_base    : same but to rear steering pivot [m]
    base_to_wheel_height : vertical drop from steering pivot to wheel axle [m]
                           (taken from the z component of the wheel joint origin
                           relative to its steering parent — always positive)
    max_steering_front : front steering joint range, as the smaller of
                         |lower| and |upper| limits [rad]
    max_steering_rear  : same for rear steering joints [rad]

    Note: wheel_radius cannot be derived from the URDF because the wheel
    links use mesh geometry (no cylinder primitive). It must be set manually.
    """
    root = ET.fromstring(urdf_text)

    # ── Collect steering joint origins (CAD frame: x=lateral, y=longitudinal) ─
    def joint_xyz(name: str) -> tuple[float, float, float]:
        return _parse_xyz(_get_joint(root, name).find("origin"))

    def joint_limit(name: str) -> tuple[float, float]:
        """Return (lower, upper) limits for a revolute joint."""
        limit = _get_joint(root, name).find("limit")
        if limit is None:
            raise ValueError(f"Joint '{name}' has no <limit> element.")
        return float(limit.get("lower", "0")), float(limit.get("upper", "0"))

    # Steering pivot positions in CAD frame
    _, bl_y, _ = joint_xyz("bl_steering")
    _, br_y, _ = joint_xyz("br_steering")
    _, fl_y, _ = joint_xyz("fl_steering")
    _, fr_y, _ = joint_xyz("fr_steering")

    # Middle wheel positions in CAD frame (no steering joint — use wheel joint)
    ml_x, ml_y, _ = joint_xyz("ml_wheel")
    mr_x, mr_y, _ = joint_xyz("mr_wheel")

    # CAD frame: y is longitudinal, forward = -y.
    # REP-105 forward distance = -(y_cad). Lateral distance = x_cad (left = +x).

    # Middle axle longitudinal position (average of left/right)
    mid_y_cad = (ml_y + mr_y) / 2.0

    # Front wheel base: how far in front of middle axle are the front pivots
    front_y_cad = (fl_y + fr_y) / 2.0
    front_wheel_base = abs(front_y_cad - mid_y_cad)

    # Rear wheel base: how far behind the middle axle are the rear pivots
    rear_y_cad = (bl_y + br_y) / 2.0
    rear_wheel_base = abs(rear_y_cad - mid_y_cad)

    # base_to_wheel_height: z drop from steering pivot down to wheel axle.
    # The wheel joint origin z gives this offset relative to the steering arm
    # parent. Take absolute value and average across all four corners.
    _, _, bl_wz = joint_xyz("bl_wheel")
    _, _, br_wz = joint_xyz("br_wheel")
    _, _, fl_wz = joint_xyz("fl_wheel")
    _, _, fr_wz = joint_xyz("fr_wheel")
    base_to_wheel_height = abs((bl_wz + br_wz + fl_wz + fr_wz) / 4.0)

    # Steering limits: use the smaller of |lower| and |upper| for a symmetric range.
    fl_lo, fl_hi = joint_limit("fl_steering")
    fr_lo, fr_hi = joint_limit("fr_steering")
    bl_lo, bl_hi = joint_limit("bl_steering")
    br_lo, br_hi = joint_limit("br_steering")

    max_steering_front = min(abs(fl_lo), abs(fl_hi), abs(fr_lo), abs(fr_hi))
    max_steering_rear = min(abs(bl_lo), abs(bl_hi), abs(br_lo), abs(br_hi))

    return {
        "front_wheel_base": front_wheel_base,
        "rear_wheel_base": rear_wheel_base,
        "base_to_wheel_height": base_to_wheel_height,
        "max_steering_front_rad": max_steering_front,
        "max_steering_rear_rad": max_steering_rear,
        "max_steering_front_deg": math.degrees(max_steering_front),
        "max_steering_rear_deg": math.degrees(max_steering_rear),
    }


def update_rover_params(urdf_filename: str = "rover.urdf",
                        config_filename: str = "../config/state_estimation_config.yaml") -> None:
    """Update rover geometry constants in state_estimation_config.yaml from the URDF.

    Derives all geometry values that can be computed from joint origins/limits.
    wheel_radius cannot be derived (mesh-only geometry) and is left unchanged.

    Args:
        urdf_filename: Filename of the URDF relative to this script's directory.
        config_filename: Path to the config yaml relative to this script's directory.
    """
    script_dir = Path(__file__).resolve().parent
    urdf_path = (script_dir / urdf_filename).resolve()
    config_path = (script_dir / config_filename).resolve()

    if not urdf_path.exists():
        raise FileNotFoundError(f"URDF not found: {urdf_path}")
    if not config_path.exists():
        raise FileNotFoundError(f"Config not found: {config_path}")

    urdf_text = urdf_path.read_text(encoding="utf-8")
    geometry = _derive_rover_geometry(urdf_text)

    config_text = config_path.read_text(encoding="utf-8")

    # Update each parameter in-place, preserving comments and formatting.
    # Matches:  <key>: <old_value> # optional comment
    replacements = {
        "front_wheel_base": (geometry["front_wheel_base"],
                             "Middle Wheel to Front Wheel distance along the Robot X-axis [m]"),
        "rear_wheel_base": (geometry["rear_wheel_base"],
                            "Middle Wheel to Rear Wheel distance along the Robot X-axis [m]"),
        "base_to_wheel_height": (geometry["base_to_wheel_height"],
                                 "Height of the steering pivot above the wheel axle [m]"),
        "max_steering_front": (geometry["max_steering_front_rad"],
                               f"Front wheel max steering angle [rad] ({geometry['max_steering_front_deg']:.1f} deg)"),
        "max_steering_rear": (geometry["max_steering_rear_rad"],
                              f"Rear wheel max steering angle [rad] ({geometry['max_steering_rear_deg']:.1f} deg)"),
    }

    for key, (value, comment) in replacements.items():
        config_text = re.sub(
            rf'({re.escape(key)}:\s*)[\d.eE+\-]+([^\n]*)',
            lambda m, v=value, c=comment: f"{m.group(1)}{v:.6f} # {c}",
            config_text,
        )
        print(f"  {key}: {value:.6f}  # {comment}")

    config_path.write_text(config_text, encoding="utf-8")
    print(f"Updated {config_path}")

# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    run_onshape_to_robot()
    clean_urdf("rover.urdf")
    print("Cleaned URDF: rover.urdf")
    print("Updating rover geometry parameters:")
    update_rover_params()
