"""
create_urdf.py
──────────────
Post-processes the URDF generated by onshape-to-robot:

  1. Rewrites mesh URIs to the correct ROS package path.
  2. Injects a `base_footprint` link as the REP-105 compliant root link,
     connected to `base_link` via a computed fixed joint that places
     base_footprint at the kinematic centre of the rover with:
       x = forward,  y = left,  z = up
  3. Corrects the zero-angle offset of the rear steering joints so that
     a joint command of 0 rad produces straight-ahead wheel alignment.

base_footprint vs base_link
────────────────────────────
`base_link` is wherever onshape-to-robot placed the exported frame — the
CAD part origin, which is generally not at the kinematic centre of the
robot and may have a different axis orientation.

`base_footprint` is the semantic root used by the ROS navigation stack
(REP-105). The fixed joint between them is computed automatically from
the steering joint positions in the URDF so it stays correct across
re-exports without any manual editing.

Frame detection
───────────────
The parser checks whether same-side joints (e.g. bl + fl = left side)
share an x or y value to determine whether the URDF is in the old CAD
frame (x = lateral, y = longitudinal, forward = -y) or already REP-105
aligned (x = forward, y = lateral). The correction rotation and
translation are derived accordingly.

Rear steering zero offset
──────────────────────────
The physical rear steering arms have a 10 degree mechanical offset from
the Onshape CAD zero position. Correcting this in the URDF requires two
coordinated changes to each affected joint:

  1. Add the offset to the joint <origin> yaw so the child link (the
     steering arm) is rotated to its true straight-ahead pose when the
     joint variable reads 0.

  2. Shift both limit bounds by the negative offset so the physical
     travel range stays unchanged. Without this the limits would be
     biased and the arm would hit a soft limit before reaching one
     extreme of its physical travel.

  Example for REAR_STEERING_ZERO_OFFSET_RAD = +0.17453 (+10 deg):
    origin yaw:   old_yaw + 0.17453
    lower limit:  old_lower - 0.17453
    upper limit:  old_upper - 0.17453
"""

from __future__ import annotations

import math
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

# Joints whose physical zero position is offset from the Onshape CAD zero.
# Each entry maps a joint name to the correction in radians to add to the
# joint origin yaw. The limit bounds are shifted by the negative of this
# value to preserve the physical range of motion.
#
# Positive = counterclockwise when viewed from above (right-hand rule, +z up).
# Negate this value if the wheels toe inward instead of pointing straight.
JOINT_ZERO_OFFSETS_RAD: dict[str, float] = {
    "bl_steering": math.radians(10.0),
    "br_steering": math.radians(10.0) * -1.0,
}


# ─────────────────────────────────────────────────────────────────────────────
# onshape-to-robot runner
# ─────────────────────────────────────────────────────────────────────────────

def run_onshape_to_robot(target_dir: str | Path | None = None) -> None:
    """Run onshape-to-robot to (re)generate the URDF and meshes.

    Args:
        target_dir: Directory to run the tool in. Defaults to the package dir.
    """
    script_dir = Path(__file__).resolve().parent   # .../perseverance/urdf
    package_dir = Path(target_dir) if target_dir else script_dir.parent
    if not package_dir.exists():
        raise FileNotFoundError(
            f"Target directory does not exist: {package_dir}")

    venv_tool = package_dir.parent / ".venv" / "bin" / "onshape-to-robot"
    cmd_path = str(venv_tool) if venv_tool.exists(
    ) else shutil.which("onshape-to-robot")
    if not cmd_path:
        raise RuntimeError(
            "onshape-to-robot not found. Install it (preferably in .venv) or add to PATH.")

    print(f"Running: {cmd_path} . (cwd={package_dir})")
    try:
        subprocess.run([cmd_path, "."], cwd=str(package_dir), check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"onshape-to-robot failed (exit {e.returncode})") from e
    print("onshape-to-robot conversion completed")


# ─────────────────────────────────────────────────────────────────────────────
# Geometry helpers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_xyz(origin_elem: ET.Element | None) -> tuple[float, float, float]:
    """Extract (x, y, z) floats from a URDF <origin xyz="..."/> element."""
    if origin_elem is None:
        return 0.0, 0.0, 0.0
    parts = origin_elem.get("xyz", "0 0 0").split()
    return float(parts[0]), float(parts[1]), float(parts[2])


def _compute_base_footprint_joint(urdf_text: str) -> tuple[float, float, float, float, float, float]:
    """
    Parse the URDF and return (tx, ty, tz, roll, pitch, yaw) for the
    base_footprint_to_base_link fixed joint.

    The translation places base_footprint at the kinematic centre of the rover
    (midpoint between front/rear wheel axles and left/right pivots).
    The rotation corrects the CAD frame orientation to REP-105.

    Frame detection
    ───────────────
    Same-side joints (e.g. bl_steering + fl_steering = left side) always share
    one coordinate:
      - If they share x  →  x is the lateral axis  →  old CAD frame (forward = -y)
      - If they share y  →  y is the lateral axis  →  REP-105 frame (forward = +x)

    This test is robust regardless of whether track width ≈ wheelbase.

    Returns
    ───────
    (tx, ty, tz, roll, pitch, yaw) in metres / radians, expressing the position
    and orientation of base_link's origin in the base_footprint frame.
    """
    root = ET.fromstring(urdf_text)

    # Collect (x, y) origins of all steering joints
    steering_origins: list[tuple[float, float]] = []
    for joint in root.iter("joint"):
        if not joint.get("name", "").endswith("_steering"):
            continue
        x, y, _ = _parse_xyz(joint.find("origin"))
        steering_origins.append((x, y))

    if len(steering_origins) < 2:
        raise ValueError(
            f"Found only {len(steering_origins)} '_steering' joints — need at least 2."
        )

    # ── Frame orientation detection ───────────────────────────────────────────
    # Group joints by rounded y value. In the old CAD frame, joints on the same
    # front/rear row share a y value but have different x values (left vs right).
    # If every y-group contains joints with varying x, then x is lateral → CAD frame.
    groups_by_y: dict[float, list[float]] = {}
    for x, y in steering_origins:
        key = round(y, 3)
        groups_by_y.setdefault(key, []).append(x)

    # Old CAD frame: each y-group (same row) has multiple distinct x values
    old_cad_frame = all(
        max(xs) - min(xs) > 0.05
        for xs in groups_by_y.values()
        if len(xs) >= 2
    )

    if old_cad_frame:
        # x = lateral (left = +x),  y = longitudinal (forward = -y)
        front_y = sum(y for _, y in steering_origins if y < 0) / max(
            1, sum(1 for _, y in steering_origins if y < 0))
        rear_y = sum(y for _, y in steering_origins if y > 0) / max(
            1, sum(1 for _, y in steering_origins if y > 0))
        left_x = sum(x for x, _ in steering_origins if x > 0) / max(
            1, sum(1 for x, _ in steering_origins if x > 0))
        right_x = sum(x for x, _ in steering_origins if x < 0) / max(
            1, sum(1 for x, _ in steering_origins if x < 0))

        kin_x_cad = (left_x + right_x) / 2.0
        kin_y_cad = (front_y + rear_y) / 2.0

        # +90° rotation: CAD x=lateral/y=longitudinal → REP x=fwd/y=left
        #   x_rep = -y_cad,   y_rep = x_cad
        # Translation: place base_link origin (0,0 in CAD) at the correct
        # position in base_footprint frame:
        #   (tx, ty) = -R(yaw) * (kin_x_cad, kin_y_cad)
        yaw = math.pi / 2.0
        tx = -(math.cos(yaw) * kin_x_cad - math.sin(yaw) * kin_y_cad)
        ty = -(math.sin(yaw) * kin_x_cad + math.cos(yaw) * kin_y_cad)

    else:
        # REP-105 already: x = forward,  y = lateral (left = +y)
        front_x = sum(x for x, _ in steering_origins if x > 0) / max(
            1, sum(1 for x, _ in steering_origins if x > 0))
        rear_x = sum(x for x, _ in steering_origins if x < 0) / max(
            1, sum(1 for x, _ in steering_origins if x < 0))
        left_y = sum(y for _, y in steering_origins if y > 0) / max(
            1, sum(1 for _, y in steering_origins if y > 0))
        right_y = sum(y for _, y in steering_origins if y < 0) / max(
            1, sum(1 for _, y in steering_origins if y < 0))

        kin_x = (front_x + rear_x) / 2.0
        kin_y = (left_y + right_y) / 2.0

        # No rotation needed — just shift to kinematic centre
        tx = -kin_x
        ty = -kin_y
        yaw = 0.0

    return tx, ty, 0.0, 0.0, 0.0, yaw


def _build_base_footprint_xml(tx: float, ty: float, tz: float,
                              roll: float, pitch: float, yaw: float) -> str:
    """Return the XML block for base_footprint and its fixed joint to base_link."""
    return (
        "\n"
        "  <!-- REP-105 semantic root link: x=forward, y=left, z=up -->\n"
        "  <!-- Placed at the kinematic centre between all wheel axles -->\n"
        "  <link name=\"base_footprint\"/>\n"
        "\n"
        "  <joint name=\"base_footprint_to_base_link\" type=\"fixed\">\n"
        "    <parent link=\"base_footprint\"/>\n"
        "    <child link=\"base_link\"/>\n"
        f"    <!-- xyz: base_link origin in base_footprint frame (auto-computed) -->\n"
        f"    <!-- rpy: CAD-frame to REP-105 correction (yaw={math.degrees(yaw):.1f} deg) -->\n"
        f"    <origin xyz=\"{tx:.6f} {ty:.6f} {tz:.6f}\""
        f" rpy=\"{roll:.6f} {pitch:.6f} {yaw:.6f}\"/>\n"
        "  </joint>\n"
    )


def _apply_joint_zero_offsets(text: str) -> str:
    """
    Correct joint origin yaws and limit bounds for joints with a mechanical
    zero offset defined in JOINT_ZERO_OFFSETS_RAD.

    For each affected joint the URDF <origin> rpy yaw is updated and both
    <limit> bounds are shifted by the negative offset so the physical
    travel range is preserved.

    This operates on the raw URDF text using targeted regex substitution
    rather than a full XML parse/serialise round-trip to avoid disturbing
    the formatting and floating-point representation of unrelated elements.

    Args:
        text: Raw URDF file content.

    Returns:
        Updated URDF content with corrected joint origins and limits.
    """
    for joint_name, offset_rad in JOINT_ZERO_OFFSETS_RAD.items():

        # Match the entire <joint name="..."> ... </joint> block.
        joint_pattern = re.compile(
            rf'(<joint\s+name="{re.escape(joint_name)}".*?</joint>)',
            re.DOTALL,
        )
        match = joint_pattern.search(text)
        if not match:
            print(
                f"  Warning: joint '{joint_name}' not found — skipping zero offset.")
            continue

        joint_xml = match.group(1)

        # ── Update origin yaw ─────────────────────────────────────────────────
        # The <origin> rpy attribute holds "roll pitch yaw" as space-separated
        # floats. We extract the current yaw, add the offset, and write it back.
        origin_match = re.search(
            r'<origin\s+([^/]*?)/?>', joint_xml, re.DOTALL)
        if not origin_match:
            print(
                f"  Warning: no <origin> in '{joint_name}' — skipping zero offset.")
            continue

        origin_tag = origin_match.group(0)
        rpy_match = re.search(r'rpy="([^"]+)"', origin_tag)

        if rpy_match:
            rpy_vals = rpy_match.group(1).split()
            roll, pitch = float(rpy_vals[0]), float(rpy_vals[1])
            old_yaw = float(rpy_vals[2])
            new_yaw = old_yaw + offset_rad
            new_rpy_str = f"{roll} {pitch} {new_yaw:.6f}"
            new_origin_tag = origin_tag.replace(rpy_match.group(0),
                                                f'rpy="{new_rpy_str}"')
        else:
            # No rpy attribute present — add it with the offset as the yaw
            new_origin_tag = origin_tag.replace(">",
                                                f' rpy="0 0 {offset_rad:.6f}">')
            old_yaw = 0.0

        joint_xml = joint_xml.replace(origin_tag, new_origin_tag)

        # ── Update limit bounds ───────────────────────────────────────────────
        # Shift both bounds by -offset so the physical travel window slides
        # with the new zero without changing its width.
        limit_match = re.search(r'<limit\s+([^/]*?)/>', joint_xml, re.DOTALL)
        if limit_match:
            limit_tag = limit_match.group(0)
            lower_match = re.search(r'lower="([^"]+)"', limit_tag)
            upper_match = re.search(r'upper="([^"]+)"', limit_tag)

            if lower_match and upper_match:
                new_lower = float(lower_match.group(1)) - offset_rad
                new_upper = float(upper_match.group(1)) - offset_rad
                new_limit = limit_tag \
                    .replace(lower_match.group(0), f'lower="{new_lower:.6f}"') \
                    .replace(upper_match.group(0), f'upper="{new_upper:.6f}"')
                joint_xml = joint_xml.replace(limit_tag, new_limit)

        text = text.replace(match.group(1), joint_xml)
        print(
            f"  Applied zero offset to '{joint_name}': "
            f"yaw {math.degrees(old_yaw):.3f} -> {math.degrees(old_yaw + offset_rad):.3f} deg, "
            f"limits shifted by {math.degrees(-offset_rad):.3f} deg"
        )

    return text


# ─────────────────────────────────────────────────────────────────────────────
# Main post-processing function
# ─────────────────────────────────────────────────────────────────────────────

def clean_urdf(urdf_filename: str) -> None:
    """Clean and post-process the URDF generated by onshape-to-robot.

    Transformations applied
    ───────────────────────
    1. Rewrite mesh URIs to the correct ROS package path.
    2. Inject a base_footprint link + fixed joint (auto-computed from wheel
       geometry) as the REP-105 compliant root link.
    3. Correct joint zero offsets for rear steering arms so that a command
       of 0 rad drives straight ahead (see JOINT_ZERO_OFFSETS_RAD).

    Args:
        urdf_filename: Filename of the URDF (e.g., 'rover.urdf').
    """
    script_dir = Path(__file__).resolve().parent
    urdf_path = (script_dir / urdf_filename).resolve()
    if not urdf_path.exists():
        raise FileNotFoundError(f"URDF file not found: {urdf_path}")

    text = urdf_path.read_text(encoding="utf-8")

    # ── Step 1: rewrite mesh URIs ─────────────────────────────────────────────
    # onshape-to-robot emits e.g. "package://meshes/foo.stl" or
    # "package://perseverance/meshes/foo.stl"; normalise both to
    # "package://perseverance/urdf/foo.stl" so RViz can resolve them.
    text = re.sub(
        r'package://[^"]*?([^/\s"]+\.stl)',
        r'package://perseverance/urdf/\1',
        text,
    )

    # ── Step 2: inject base_footprint (idempotent — skipped if already present) ──
    if "base_footprint" not in text:
        tx, ty, tz, roll, pitch, yaw = _compute_base_footprint_joint(text)
        footprint_xml = _build_base_footprint_xml(tx, ty, tz, roll, pitch, yaw)

        # Insert immediately after the opening <robot ...> tag
        m = re.search(r"<robot\b[^>]*>", text)
        if not m:
            raise ValueError("Could not find <robot> tag in URDF.")
        text = text[:m.end()] + footprint_xml + text[m.end():]

        print(
            f"Injected base_footprint: "
            f"xyz=({tx:.4f}, {ty:.4f}, {tz:.4f})  "
            f"yaw={math.degrees(yaw):.1f} deg"
        )
    else:
        print("base_footprint already present — skipping injection.")

    # ── Step 3: correct rear steering joint zero offsets ─────────────────────
    print("Applying joint zero offsets:")
    text = _apply_joint_zero_offsets(text)

    urdf_path.write_text(text, encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run_onshape_to_robot()
    clean_urdf("rover.urdf")
    print("Cleaned URDF: rover.urdf")
