name: Auto-format C++ code, Build, and Test ROS Package

on:
  push:
    branches:
      - main

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Install Eigen3
        run: apt-get update && apt-get install -y libeigen3-dev
        
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: state_estimation
          target-ros2-distro: jazzy
